package com.shecancode.attendence.registration.Enum;

public enum Occupation {
    EMPLOYED,
    ATTENDING_UNIVERSITY_NOT_EMPLOYED,
    EMPLOYED_ATTENDING_UNIVERSITY,
    ATTENDING_ADVANCED_TRAINING_AND_UNIVERSITY,
    NOT_EMPLOYED_NOT_IN_SCHOOL_NOT_IN_ANY_TRAINING,
    INTERNSHIP
}
